name: java invocation quickstart

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/invoke_java.yaml
      - invocation/java/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/invoke_java.yaml
      - invocation/java/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    environment: shared-production

    if: github.repository_owner == 'diagridio'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: build local
        run: |
          cd invocation/java
          mvn clean install -f ./client && mvn clean install -f ./server

      - name: Configure AWS credentials
        if: github.event_name != 'pull_request'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_CI_ROLE }}
          aws-region: ${{ vars.AWS_CI_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name != 'pull_request'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set up Docker Buildx
        if: github.event_name != 'pull_request'
        uses: docker/setup-buildx-action@v3.6.1

      - name: build and push client container
        if: github.event_name != 'pull_request'
        working-directory: invocation/java/client
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ steps.login-ecr.outputs.registry }}/${{ vars.AWS_PUBLIC_ECR_ALIAS }}/invoke-java-client-qs . --push

      - name: build and push server container
        if: github.event_name != 'pull_request'
        working-directory: invocation/java/server
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ steps.login-ecr.outputs.registry }}/${{ vars.AWS_PUBLIC_ECR_ALIAS }}/invoke-java-server-qs . --push
