name: Build and Push KeyValue JavaScript Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'keyvalue/javascript/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'    
    environment: development
    env:
      GCP_PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'
      GCP_DOCKER_REPOSITORY: '${{ secrets.GCP_DOCKER_REPOSITORY }}'
      GCP_CONTAINER_REGISTRY_HOST: '${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}'
      IMAGE_NAME: catalyst-quickstarts/keyvalue-javascript

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        name: Configure Google Credentials
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{ secrets.SERVICE_ACCOUNT}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Auth
        uses: 'docker/login-action@v3'
        with:
          registry: '${{ env.GCP_CONTAINER_REGISTRY_HOST }}'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          
      - name: Build and Push Docker Image (AMD, ARM)
        working-directory: keyvalue/javascript
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t $GCP_CONTAINER_REGISTRY_HOST/$GCP_PROJECT_ID/$GCP_DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_SHA . --push