name: csharp pubsub quickstart

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/pubsub_csharp.yaml
      - pubsub/csharp/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    environment: shared-production
    # Only run on main repo (not on forks)
    if: github.repository_owner == 'diagridio'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: build local
        run: |
          cd pubsub/csharp
          donet build ./publisher && dotnet build ./subscriber

      - name: build publisher image
        run: |
          cd pubsub/csharp/publisher
          docker buildx build --platform linux/amd64 -t pubsub-csharp-publisher .

      - name: build subscriber image
        run: |
          cd pubsub/csharp/subscriber
          docker buildx build --platform linux/amd64 -t pubsub-csharp-subscriber .

      - name: Configure AWS credentials
        if: github.event_name != 'pull_request'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_CI_ROLE }}
          aws-region: ${{ vars.AWS_CI_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name != 'pull_request'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: push publisher image
        if: github.event_name != 'pull_request'
        env:
          PUBLIC_ECR: "${{ steps.login-ecr.outputs.registry }}/${{ vars.AWS_PUBLIC_ECR_ALIAS }}/pubsub-csharp-publisher"
        run: |
          docker tag pubsub-csharp-publisher:latest $PUBLIC_ECR:latest
          docker push $PUBLIC_ECR:latest

      - name: push subscriber image
        if: github.event_name != 'pull_request'
        env:
          PUBLIC_ECR: "${{ steps.login-ecr.outputs.registry }}/${{ vars.AWS_PUBLIC_ECR_ALIAS }}/pubsub-csharp-subscriber"
        run: |
          docker tag pubsub-csharp-subscriber:latest $PUBLIC_ECR:latest
          docker push $PUBLIC_ECR:latest
