name: python state quickstart

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/state_python.yaml
      - state/python/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    environment: shared-production
    # Only run on main repo (not on forks)
    if: github.repository_owner == 'diagridio'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: build local
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: build order-app image
        run: |
          cd python
          docker buildx build --platform linux/amd64 -t state-python .

      - name: Configure AWS credentials
        if: github.event_name != 'pull_request'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_CI_ROLE }}
          aws-region: ${{ vars.AWS_CI_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name != 'pull_request'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: push order-app image
        if: github.event_name != 'pull_request'
        env:
          PUBLIC_ECR: "${{ steps.login-ecr.outputs.registry }}/${{ vars.AWS_PUBLIC_ECR_ALIAS }}/state-python"
        run: |
          docker tag state-python:latest $PUBLIC_ECR:latest
          docker push $PUBLIC_ECR:latest
