apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: registry-state
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: "foo"
  - name: enableTLS
    value: "false"

